#
#                GLWT(Good Luck With That) Public License
#                  Copyright (c) Everyone, except Author
# 
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever they want with this software but at their OWN RISK.
# 
#                             Preamble
# 
# The author has absolutely no clue what the code in this project does.
# It might just work or not, there is no third option.
# 
# 
#                 GOOD LUCK WITH THAT PUBLIC LICENSE
#    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION
# 
#   0. You just DO WHATEVER YOU WANT TO as long as you NEVER LEAVE A
# TRACE TO TRACK THE AUTHOR of the original product to blame for or hold
# responsible.
# 
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# 
# Good luck and Godspeed.
#

# General settings.
# Verbose ? If true, console will log informations and users with wc.verbose permission will receive messages about WeatherEvents.
verbose: false
# The level of verbosity :
# 0 : Errors.
# 1 : Errors + Warnings.
# 2 : Errors + Warnings + Info.
# 3 : Errors + Warnings + Info + Death events.
# 4 : Errors + Warnings + Info + Death events + debug info.
verbose-level: 0


# Death penalties settings.
lose-exp: true
lose-backpack: true
lose-belt: true
lose-equipment: true

# Exp penalty settings [0..100]%.
exp-penalty: 100

# Items durability penalty (when equipment is not lost on death) [0..100]%.
dura-penalty: 100
item-break: true